import { Inter } from "next/font/google";

import '@/app/resources/css/global.css';
import { AuthProvider } from "./context/AuthContext";
import BaseLayout from "./layouts/BaseLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <AuthProvider>

          <BaseLayout>

            {children}

          </BaseLayout>

        </AuthProvider>

      </body>
    </html>
  );
}
