import { Inter } from "next/font/google";
import Sidebar from "./components/Sidebar";

import '@/app/resources/css/global.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Sidebar />
        
        {children}

      </body>
    </html>
  );
}
